FROM nikolaik/python-nodejs:latest

ARG UID=1000
ARG GID=1000

ENV APPHOME=/home/pn
ENV APPDIR=$APPHOME/app
ENV BINDMOUNT_VOL=./data
ENV GIGAOHMBIO_URL=$BINDMOUNT_VOL/latest-video-url.txt
ENV GIGAOHMBIO_DL=$BINDMOUNT_VOL/dl-output.txt
ENV GIGAOHMBIO_LOG=$BINDMOUNT_VOL/log.txt

USER root
WORKDIR /app
# set userid and groupid of the pn user from the host
# fix volume access issues across hosts
RUN <<EOF
usermod -u $UID -g pn -o pn
groupmod -g $GID -o pn
EOF
# install system prerequisites
RUN <<EOF
apt-get update
apt-get install pipx ffmpeg gnupg wget -y
wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg
sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
apt-get update
apt-get install google-chrome-stable -y --no-install-recommends
rm -rf /var/lib/apt/lists/*
EOF

USER pn
WORKDIR $APPDIR
COPY --chmod=755 entrypoint-download.sh .
# install twitch-dl for pn, test access
ENV PATH="$APPHOME/.local/bin:$PATH"
RUN <<EOF
pipx install twitch-dl
pipx ensurepath
# check twitch-dl
twitch-dl --version
# check ffmpeg, too
ffmpeg -h
EOF

ENTRYPOINT ["/home/pn/app/entrypoint-download.sh"]