FROM nikolaik/python-nodejs:latest

ARG UID=1000
ARG GID=1000

ENV APPHOME=/home/pn
ENV APPDIR=$APPHOME/app
ENV BINDMOUNT_VOL=./data
ENV GIGAOHMBIO_URL=./data/latest-video-url.txt
ENV GIGAOHMBIO_DL=./data/dl-output.txt
ENV GIGAOHMBIO_LOG=./data/log.txt

USER root
WORKDIR /app
# set userid and groupid of the pn user from the host
# fix volume access issues across hosts
RUN <<EOF
usermod -u $UID -g pn -o pn
groupmod -g $GID -o pn
EOF
# install system prerequisites
RUN <<EOF
apt-get update
apt-get install pipx ffmpeg ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils -y
EOF

USER pn
WORKDIR $APPDIR
COPY --chmod=755 entrypoint-download.sh .
# install twitch-dl for pn, test access
ENV PATH="$APPHOME/.local/bin:$PATH"
RUN <<EOF
pipx install twitch-dl
pipx ensurepath
# check twitch-dl
twitch-dl --version
# check ffmpeg, too
ffmpeg -h
EOF

ENTRYPOINT ["/home/pn/app/entrypoint-download.sh"]